//
//  References.swift
//  Skillbox Course work 1.0
//
//  Created by Алёша on 08.09.2020.
//  Copyright © 2020 Алёша. All rights reserved.
//

import Foundation
import UIKit

//references
var secondaryVC_1 = SecondaryVC_1()
var secondaryVC_2 = SecondaryVC_2()




var operations = Operations()
var stations = Stations()
var viewController = ViewController()
var workWithChooseSlidingView = WorkWithChooseSlidingView()
var creatingStationConnections = CreatingStationConnections()

var viewsArray = [UIView?]()
var buttonOutletsArray = [UIButton]()
var connectionOutletsArray = [RotateView]()
var connectionsArray = [RotateView]()
var buttonsArray = [UIButton]()

//adding stations to array
let stationsArray = [
    
    stations.line1Station1,
    stations.line1Station2,
    stations.line1Station3,
    stations.line1Station4,
    stations.line1Station5,
    stations.line1Station6,
    stations.line1Station7,
    stations.line1Station8,
    stations.line1Station9,
    stations.line1Station10,
    stations.line1Station11,
    stations.line1Station12,
    stations.line1Station13,
    stations.line1Station14,
    stations.line1Station15,
    stations.line1Station16,
    stations.line1Station17,
    stations.line1Station18,
    stations.line1Station19,
    stations.line1Station20,
    stations.line1Station21,
    stations.line1Station22,
    stations.line1Station23,
    stations.line1Station24,
    stations.line1Station25,
    stations.line1Station26,
    
    stations.line2Station1,
    stations.line2Station2,
    stations.line2Station3,
    stations.line2Station4,
    stations.line2Station5,
    stations.line2Station6,
    stations.line2Station7,
    stations.line2Station8,
    stations.line2Station9,
    stations.line2Station10,
    stations.line2Station11,
    stations.line2Station12,
    stations.line2Station13,
    stations.line2Station14,
    stations.line2Station15,
    stations.line2Station16,
    stations.line2Station17,
    stations.line2Station18,
    stations.line2Station19,
    stations.line2Station20,
    stations.line2Station21,
    stations.line2Station22,
    stations.line2Station23,
    stations.line2Station24,
         
    stations.line3Station1,
    stations.line3Station2,
    stations.line3Station3,
    stations.line3Station4,
    stations.line3Station5,
    stations.line3Station6,
    stations.line3Station7,
    stations.line3Station8,
    stations.line3Station9,
    stations.line3Station10,
    stations.line3Station11,
    stations.line3Station12,
    stations.line3Station13,
    stations.line3Station14,
    stations.line3Station15,
    stations.line3Station16,
    stations.line3Station17,
    stations.line3Station18,
    stations.line3Station19,
    stations.line3Station20,
    stations.line3Station21,
    stations.line3Station22,
         
    stations.line4Station1,
    stations.line4Station2,
    stations.line4Station3,
    stations.line4Station4,
    stations.line4Station5,
    stations.line4Station6,
    stations.line4Station7,
    stations.line4Station8,
    stations.line4Station9,
    stations.line4Station10,
    stations.line4Station11,
    stations.line4Station12,
    stations.line4Station13,

    stations.line5Station1,
    stations.line5Station2,
    stations.line5Station3,
    stations.line5Station4,
    stations.line5Station5,
    stations.line5Station6,
    stations.line5Station7,
    stations.line5Station8,
    stations.line5Station9,
    stations.line5Station10,
    stations.line5Station11,
    stations.line5Station12,
    
    stations.line6Station1,
    stations.line6Station2,
    stations.line6Station3,
    stations.line6Station4,
    stations.line6Station5,
    stations.line6Station6,
    stations.line6Station7,
    stations.line6Station8,
    stations.line6Station9,
    stations.line6Station10,
    stations.line6Station11,
    stations.line6Station12,
    stations.line6Station13,
    stations.line6Station14,
    stations.line6Station15,
    stations.line6Station16,
    stations.line6Station17,
    stations.line6Station18,
    stations.line6Station19,
    stations.line6Station20,
    stations.line6Station21,
    stations.line6Station22,
    stations.line6Station23,
    stations.line6Station24,
    
    stations.line7Station1,
    stations.line7Station2,
    stations.line7Station3,
    stations.line7Station4,
    stations.line7Station5,
    stations.line7Station6,
    stations.line7Station7,
    stations.line7Station8,
    stations.line7Station9,
    stations.line7Station10,
    stations.line7Station11,
    stations.line7Station12,
    stations.line7Station13,
    stations.line7Station14,
    stations.line7Station15,
    stations.line7Station16,
    stations.line7Station17,
    stations.line7Station18,
    stations.line7Station19,
    stations.line7Station20,
    stations.line7Station21,
    stations.line7Station22,
    stations.line7Station23,
    
    stations.line8Station1,
    stations.line8Station2,
    stations.line8Station3,
    stations.line8Station4,
    stations.line8Station5,
    stations.line8Station6,
    stations.line8Station7,
    stations.line8Station8,
    stations.line8Station9,
    stations.line8Station10,
    stations.line8Station11,
    stations.line8Station12,
    stations.line8Station13,
    stations.line8Station14,
    stations.line8Station15,
    stations.line8Station16,
    stations.line8Station17,
    stations.line8Station18,
    stations.line8Station19,
    stations.line8Station20,

    stations.line9Station1,
    stations.line9Station2,
    stations.line9Station3,
    stations.line9Station4,
    stations.line9Station5,
    stations.line9Station6,
    stations.line9Station7,
    stations.line9Station8,
    stations.line9Station9,
    stations.line9Station10,
    stations.line9Station11,
    stations.line9Station12,
    stations.line9Station13,
    stations.line9Station14,
    stations.line9Station15,
    stations.line9Station16,
    stations.line9Station17,
    stations.line9Station18,
    stations.line9Station19,
    stations.line9Station20,
    stations.line9Station21,
    stations.line9Station22,
    stations.line9Station23,
    stations.line9Station24,
    stations.line9Station25,
    
    stations.line10Station1,
    stations.line10Station2,
    stations.line10Station3,
    stations.line10Station4,
    stations.line10Station5,
    stations.line10Station6,
    stations.line10Station7,
    stations.line10Station8,
    stations.line10Station9,
    stations.line10Station10,
    stations.line10Station11,
    stations.line10Station12,
    stations.line10Station13,
    stations.line10Station14,
    stations.line10Station15,
    stations.line10Station16,
    stations.line10Station17,
    stations.line10Station18,
    stations.line10Station19,
    stations.line10Station20,
    stations.line10Station21,
    stations.line10Station22,
    stations.line10Station23,
    
    stations.line11Station1,
    stations.line11Station2,
    stations.line11Station3,
    stations.line11Station4,
    stations.line11Station5,
    stations.line11Station6,
    
    stations.line12Station1,
    stations.line12Station2,
    stations.line12Station3,
    stations.line12Station4,
    stations.line12Station5,
    stations.line12Station6,
    stations.line12Station7,
    
    stations.line14Station1,
    stations.line14Station2,
    stations.line14Station3,
    stations.line14Station4,
    stations.line14Station5,
    stations.line14Station6,
    stations.line14Station7,
    stations.line14Station8,
    stations.line14Station9,
    stations.line14Station10,
    stations.line14Station11,
    stations.line14Station12,
    stations.line14Station13,
    stations.line14Station14,
    stations.line14Station15,
    stations.line14Station16,
    stations.line14Station17,
    stations.line14Station18,
    stations.line14Station19,
    stations.line14Station20,
    stations.line14Station21,
    stations.line14Station22,
    stations.line14Station23,
    stations.line14Station24,
    stations.line14Station25,
    stations.line14Station26,
    stations.line14Station27,
    stations.line14Station28,
    stations.line14Station29,
    stations.line14Station30,
    stations.line14Station31,
    
    stations.line15Station1,
    stations.line15Station2,
    stations.line15Station3,
    stations.line15Station4,
    stations.line15Station5,
    stations.line15Station6,
    stations.line15Station7,
    stations.line15Station8,
    stations.line15Station9,
    stations.line15Station10,
    stations.line15Station11,
    
    stations.lineD1Station1,
    stations.lineD1Station2,
    stations.lineD1Station3,
    stations.lineD1Station4,
    stations.lineD1Station5,
    stations.lineD1Station6,
    stations.lineD1Station7,
    stations.lineD1Station8,
    stations.lineD1Station9,
    stations.lineD1Station10,
    stations.lineD1Station11,
    stations.lineD1Station12,
    stations.lineD1Station13,
    stations.lineD1Station14,
    stations.lineD1Station15,
    stations.lineD1Station16,
    stations.lineD1Station17,
    stations.lineD1Station18,
    stations.lineD1Station19,
    stations.lineD1Station20,
    stations.lineD1Station21,
    stations.lineD1Station22,
    stations.lineD1Station23,
    stations.lineD1Station24,
    stations.lineD1Station25,

    stations.lineD2Station1,
    stations.lineD2Station2,
    stations.lineD2Station3,
    stations.lineD2Station4,
    stations.lineD2Station5,
    stations.lineD2Station6,
    stations.lineD2Station7,
    stations.lineD2Station8,
    stations.lineD2Station9,
    stations.lineD2Station10,
    stations.lineD2Station11,
    stations.lineD2Station12,
    stations.lineD2Station13,
    stations.lineD2Station14,
    stations.lineD2Station15,
    stations.lineD2Station16,
    stations.lineD2Station17,
    stations.lineD2Station18,
    stations.lineD2Station19,
    stations.lineD2Station20,
    stations.lineD2Station21,
    stations.lineD2Station22,
    stations.lineD2Station23,
    stations.lineD2Station24,
    stations.lineD2Station25,
    stations.lineD2Station26,
    stations.lineD2Station27,
    stations.lineD2Station28,
    stations.lineD2Station29,
    stations.lineD2Station30,
    stations.lineD2Station31,
    stations.lineD2Station32,
    stations.lineD2Station33,
    stations.lineD2Station34,
    stations.lineD2Station35

]



