//
//  Stations.swift
//  Skillbox Course work 1.0
//
//  Created by Алёша on 28.07.2020.
//  Copyright © 2020 Алёша. All rights reserved.
//

import Foundation


class Stations {
    
    //Line 1 - Сокольническая
    let line1Station1 = StationNode(name: "Бульвар Рокоссовского", line: "Сокольническая линия")
    let line1Station2 = StationNode(name: "Черкизовская", line: "Сокольническая линия")
    let line1Station3 = StationNode(name: "Преображенская площадь", line: "Сокольническая линия")
    let line1Station4 = StationNode(name: "Сокольники", line: "Сокольническая линия")
    let line1Station5 = StationNode(name: "Красносельская", line: "Сокольническая линия")
    let line1Station6 = StationNode(name: "Комсомольская", line: "Сокольническая линия")
    let line1Station7 = StationNode(name: "Красные Ворота", line: "Сокольническая линия")
    let line1Station8 = StationNode(name: "Чистые пруды", line: "Сокольническая линия")
    let line1Station9 = StationNode(name: "Лубянка", line: "Сокольническая линия")
    let line1Station10 = StationNode(name: "Охотный Ряд", line: "Сокольническая линия")
    let line1Station11 = StationNode(name: "Библиотека имени Ленина", line: "Сокольническая линия")
    let line1Station12 = StationNode(name: "Кропоткинская", line: "Сокольническая линия")
    let line1Station13 = StationNode(name: "Парк культуры", line: "Сокольническая линия")
    let line1Station14 = StationNode(name: "Фрунзенская", line: "Сокольническая линия")
    let line1Station15 = StationNode(name: "Спортивная", line: "Сокольническая линия")
    let line1Station16 = StationNode(name: "Воробьёвы горы", line: "Сокольническая линия")
    let line1Station17 = StationNode(name: "Университет", line: "Сокольническая линия")
    let line1Station18 = StationNode(name: "Проспект Вернадского", line: "Сокольническая линия")
    let line1Station19 = StationNode(name: "Юго-Западная", line: "Сокольническая линия")
    let line1Station20 = StationNode(name: "Тропарёво", line: "Сокольническая линия")
    let line1Station21 = StationNode(name: "Румянцево", line: "Сокольническая линия")
    let line1Station22 = StationNode(name: "Саларьево", line: "Сокольническая линия")
    let line1Station23 = StationNode(name: "Филатов Луг", line: "Сокольническая линия")
    let line1Station24 = StationNode(name: "Прокшино", line: "Сокольническая линия")
    let line1Station25 = StationNode(name: "Ольховая", line: "Сокольническая линия")
    let line1Station26 = StationNode(name: "Коммунарка", line: "Сокольническая линия")


    
    //Line 2 - Замоскворецкая
    let line2Station1 = StationNode(name: "Ховрино", line: "Замоскворецкая линия")
    let line2Station2 = StationNode(name: "Беломорская", line: "Замоскворецкая линия")
    let line2Station3 = StationNode(name: "Речной вокзал", line: "Замоскворецкая линия")
    let line2Station4 = StationNode(name: "Водный стадион", line: "Замоскворецкая линия")
    let line2Station5 = StationNode(name: "Войковская", line: "Замоскворецкая линия")
    let line2Station6 = StationNode(name: "Сокол", line: "Замоскворецкая линия")
    let line2Station7 = StationNode(name: "Аэропорт", line: "Замоскворецкая линия")
    let line2Station8 = StationNode(name: "Динамо", line: "Замоскворецкая линия")
    let line2Station9 = StationNode(name: "Белорусская", line: "Замоскворецкая линия")
    let line2Station10 = StationNode(name: "Маяковская", line: "Замоскворецкая линия")
    let line2Station11 = StationNode(name: "Тверская", line: "Замоскворецкая линия")
    let line2Station12 = StationNode(name: "Театральная", line: "Замоскворецкая линия")
    let line2Station13 = StationNode(name: "Новокузнецкая", line: "Замоскворецкая линия")
    let line2Station14 = StationNode(name: "Павелецкая", line: "Замоскворецкая линия")
    let line2Station15 = StationNode(name: "Автозаводская", line: "Замоскворецкая линия")
    let line2Station16 = StationNode(name: "Технопарк", line: "Замоскворецкая линия")
    let line2Station17 = StationNode(name: "Каширская", line: "Замоскворецкая линия")
    let line2Station18 = StationNode(name: "Коломенская", line: "Замоскворецкая линия")
    let line2Station19 = StationNode(name: "Кантемировская", line: "Замоскворецкая линия")
    let line2Station20 = StationNode(name: "Царицыно", line: "Замоскворецкая линия")
    let line2Station21 = StationNode(name: "Орехово", line: "Замоскворецкая линия")
    let line2Station22 = StationNode(name: "Домодедовская", line: "Замоскворецкая линия")
    let line2Station23 = StationNode(name: "Красногвардейская", line: "Замоскворецкая линия")
    let line2Station24 = StationNode(name: "Алма-Атинская", line: "Замоскворецкая линия")
    
    
    
    //Line 3 - Арбатско-Покровская
    let line3Station1 = StationNode(name: "Пятницкое шоссе", line: "Арбатско-Покровская линия")
    let line3Station2 = StationNode(name: "Митино", line: "Арбатско-Покровская линия")
    let line3Station3 = StationNode(name: "Волоколамская", line: "Арбатско-Покровская линия")
    let line3Station4 = StationNode(name: "Мякинино", line: "Арбатско-Покровская линия")
    let line3Station5 = StationNode(name: "Строгино", line: "Арбатско-Покровская линия")
    let line3Station6 = StationNode(name: "Крылатское", line: "Арбатско-Покровская линия")
    let line3Station7 = StationNode(name: "Молодёжная", line: "Арбатско-Покровская линия")
    let line3Station8 = StationNode(name: "Кунцевская", line: "Арбатско-Покровская линия")
    let line3Station9 = StationNode(name: "Славянский бульвар", line: "Арбатско-Покровская линия")
    let line3Station10 = StationNode(name: "Парк Победы", line: "Арбатско-Покровская линия")
    let line3Station11 = StationNode(name: "Киевская", line: "Арбатско-Покровская линия")
    let line3Station12 = StationNode(name: "Смоленская", line: "Арбатско-Покровская линия")
    let line3Station13 = StationNode(name: "Арбатская", line: "Арбатско-Покровская линия")
    let line3Station14 = StationNode(name: "Площадь Революции", line: "Арбатско-Покровская линия")
    let line3Station15 = StationNode(name: "Курская", line: "Арбатско-Покровская линия")
    let line3Station16 = StationNode(name: "Бауманская", line: "Арбатско-Покровская линия")
    let line3Station17 = StationNode(name: "Электрозаводская", line: "Арбатско-Покровская линия")
    let line3Station18 = StationNode(name: "Семёновская", line: "Арбатско-Покровская линия")
    let line3Station19 = StationNode(name: "Партизанская", line: "Арбатско-Покровская линия")
    let line3Station20 = StationNode(name: "Измайловская", line: "Арбатско-Покровская линия")
    let line3Station21 = StationNode(name: "Первомайская", line: "Арбатско-Покровская линия")
    let line3Station22 = StationNode(name: "Щёлковская", line: "Арбатско-Покровская линия")


    
    //Line 4 - Филёвская
    let line4Station1 = StationNode(name: "Кунцевская", line: "Филёвская линия")
    let line4Station2 = StationNode(name: "Пионерская", line: "Филёвская линия")
    let line4Station3 = StationNode(name: "Филёвский парк", line: "Филёвская линия")
    let line4Station4 = StationNode(name: "Багратионовская", line: "Филёвская линия")
    let line4Station5 = StationNode(name: "Фили", line: "Филёвская линия")
    let line4Station6 = StationNode(name: "Кутузовская", line: "Филёвская линия")
    let line4Station7 = StationNode(name: "Студенческая", line: "Филёвская линия")
    let line4Station8 = StationNode(name: "Киевская", line: "Филёвская линия")
    let line4Station9 = StationNode(name: "Смоленская", line: "Филёвская линия")
    let line4Station10 = StationNode(name: "Арбатская", line: "Филёвская линия")
    let line4Station11 = StationNode(name: "Александровский сад", line: "Филёвская линия")
    let line4Station12 = StationNode(name: "Выставочная", line: "Филёвская линия")
    let line4Station13 = StationNode(name: "Международная", line: "Филёвская линия")


    
    //Line 5 - Кольцевая
    let line5Station1 = StationNode(name: "Краснопресненская", line: "Кольцевая линия")
    let line5Station2 = StationNode(name: "Белорусская", line: "Кольцевая линия")
    let line5Station3 = StationNode(name: "Новослободская", line: "Кольцевая линия")
    let line5Station4 = StationNode(name: "Проспект Мира", line: "Кольцевая линия")
    let line5Station5 = StationNode(name: "Комсомольская", line: "Кольцевая линия")
    let line5Station6 = StationNode(name: "Курская", line: "Кольцевая линия")
    let line5Station7 = StationNode(name: "Таганская", line: "Кольцевая линия")
    let line5Station8 = StationNode(name: "Павелецкая", line: "Кольцевая линия")
    let line5Station9 = StationNode(name: "Добрынинская", line: "Кольцевая линия")
    let line5Station10 = StationNode(name: "Октябрьская", line: "Кольцевая линия")
    let line5Station11 = StationNode(name: "Парк культуры", line: "Кольцевая линия")
    let line5Station12 = StationNode(name: "Киевская", line: "Кольцевая линия")
    
    
    //Line 6 - Калужско-Рижская
    let line6Station1 = StationNode(name: "Медведково", line: "Калужско-Рижская линия")
    let line6Station2 = StationNode(name: "Бабушкинская", line: "Калужско-Рижская линия")
    let line6Station3 = StationNode(name: "Свиблово", line: "Калужско-Рижская линия")
    let line6Station4 = StationNode(name: "Ботанический сад", line: "Калужско-Рижская линия")
    let line6Station5 = StationNode(name: "ВДНХ", line: "Калужско-Рижская линия")
    let line6Station6 = StationNode(name: "Алексеевская", line: "Калужско-Рижская линия")
    let line6Station7 = StationNode(name: "Рижская", line: "Калужско-Рижская линия")
    let line6Station8 = StationNode(name: "Проспект Мира", line: "Калужско-Рижская линия")
    let line6Station9 = StationNode(name: "Сухаревская", line: "Калужско-Рижская линия")
    let line6Station10 = StationNode(name: "Тургеневская", line: "Калужско-Рижская линия")
    let line6Station11 = StationNode(name: "Китай-город", line: "Калужско-Рижская линия")
    let line6Station12 = StationNode(name: "Третьяковская", line: "Калужско-Рижская линия")
    let line6Station13 = StationNode(name: "Октябрьская", line: "Калужско-Рижская линия")
    let line6Station14 = StationNode(name: "Шаболовская", line: "Калужско-Рижская линия")
    let line6Station15 = StationNode(name: "Ленинский проспект", line: "Калужско-Рижская линия")
    let line6Station16 = StationNode(name: "Академическая", line: "Калужско-Рижская линия")
    let line6Station17 = StationNode(name: "Профсоюзная", line: "Калужско-Рижская линия")
    let line6Station18 = StationNode(name: "Новые Черёмушки", line: "Калужско-Рижская линия")
    let line6Station19 = StationNode(name: "Калужская", line: "Калужско-Рижская линия")
    let line6Station20 = StationNode(name: "Беляево", line: "Калужско-Рижская линия")
    let line6Station21 = StationNode(name: "Коньково", line: "Калужско-Рижская линия")
    let line6Station22 = StationNode(name: "Тёплый Стан", line: "Калужско-Рижская линия")
    let line6Station23 = StationNode(name: "Ясенево", line: "Калужско-Рижская линия")
    let line6Station24 = StationNode(name: "Новоясеневская", line: "Калужско-Рижская линия")

    
    //Line 7 - Таганско-Краснопресненская
    let line7Station1 = StationNode(name: "Планерная", line: "Таганско-Краснопресненская линия")
    let line7Station2 = StationNode(name: "Сходненская", line: "Таганско-Краснопресненская линия")
    let line7Station3 = StationNode(name: "Тушинская", line: "Таганско-Краснопресненская линия")
    let line7Station4 = StationNode(name: "Спартак", line: "Таганско-Краснопресненская линия")
    let line7Station5 = StationNode(name: "Щукинская", line: "Таганско-Краснопресненская линия")
    let line7Station6 = StationNode(name: "Октябрьское Поле", line: "Таганско-Краснопресненская линия")
    let line7Station7 = StationNode(name: "Полежаевская", line: "Таганско-Краснопресненская линия")
    let line7Station8 = StationNode(name: "Беговая", line: "Таганско-Краснопресненская линия")
    let line7Station9 = StationNode(name: "Улица 1905 года", line: "Таганско-Краснопресненская линия")
    let line7Station10 = StationNode(name: "Баррикадная", line: "Таганско-Краснопресненская линия")
    let line7Station11 = StationNode(name: "Пушкинская", line: "Таганско-Краснопресненская линия")
    let line7Station12 = StationNode(name: "Кузнецкий Мост", line: "Таганско-Краснопресненская линия")
    let line7Station13 = StationNode(name: "Китай-город", line: "Таганско-Краснопресненская линия")
    let line7Station14 = StationNode(name: "Таганская", line: "Таганско-Краснопресненская линия")
    let line7Station15 = StationNode(name: "Пролетарская", line: "Таганско-Краснопресненская линия")
    let line7Station16 = StationNode(name: "Волгоградский проспект", line: "Таганско-Краснопресненская линия")
    let line7Station17 = StationNode(name: "Текстильщики", line: "Таганско-Краснопресненская линия")
    let line7Station18 = StationNode(name: "Кузьминки", line: "Таганско-Краснопресненская линия")
    let line7Station19 = StationNode(name: "Рязанский проспект", line: "Таганско-Краснопресненская линия")
    let line7Station20 = StationNode(name: "Выхино", line: "Таганско-Краснопресненская линия")
    let line7Station21 = StationNode(name: "Лермонтовский проспект", line: "Таганско-Краснопресненская линия")
    let line7Station22 = StationNode(name: "Жулебино", line: "Таганско-Краснопресненская линия")
    let line7Station23 = StationNode(name: "Котельники", line: "Таганско-Краснопресненская линия")
    
    
    //Line 8 - Калининская
    let line8Station1 = StationNode(name: "Новокосино", line: "Калининская линия")
    let line8Station2 = StationNode(name: "Новогиреево", line: "Калининская линия")
    let line8Station3 = StationNode(name: "Перово", line: "Калининская линия")
    let line8Station4 = StationNode(name: "Шоссе Энтузиастов", line: "Калининская линия")
    let line8Station5 = StationNode(name: "Авиамоторная", line: "Калининская линия")
    let line8Station6 = StationNode(name: "Площадь Ильича", line: "Калининская линия")
    let line8Station7 = StationNode(name: "Марксистская", line: "Калининская линия")
    let line8Station8 = StationNode(name: "Третьяковская", line: "Калининская линия")
    let line8Station9 = StationNode(name: "Деловой центр", line: "Калининская линия")
    let line8Station10 = StationNode(name: "Парк Победы", line: "Калининская линия")
    let line8Station11 = StationNode(name: "Минская", line: "Калининская линия")
    let line8Station12 = StationNode(name: "Ломоносовский проспект", line: "Калининская линия")
    let line8Station13 = StationNode(name: "Раменки", line: "Калининская линия")
    let line8Station14 = StationNode(name: "Мичуринский проспект", line: "Калининская линия")
    let line8Station15 = StationNode(name: "Озёрная", line: "Калининская линия")
    let line8Station16 = StationNode(name: "Говорово", line: "Калининская линия")
    let line8Station17 = StationNode(name: "Солнцево", line: "Калининская линия")
    let line8Station18 = StationNode(name: "Боровское шоссе", line: "Калининская линия")
    let line8Station19 = StationNode(name: "Новопеределкино", line: "Калининская линия")
    let line8Station20 = StationNode(name: "Рассказовка", line: "Калининская линия")
    
    
    //Line 9 - Серпуховско-Тимирязевская
    let line9Station1 = StationNode(name: "Алтуфьево", line: "Серпуховско-Тимирязевская линия")
    let line9Station2 = StationNode(name: "Бибирево", line: "Серпуховско-Тимирязевская линия")
    let line9Station3 = StationNode(name: "Отрадное", line: "Серпуховско-Тимирязевская линия")
    let line9Station4 = StationNode(name: "Владыкино", line: "Серпуховско-Тимирязевская линия")
    let line9Station5 = StationNode(name: "Петровско-Разумовская", line: "Серпуховско-Тимирязевская линия")
    let line9Station6 = StationNode(name: "Тимирязевская", line: "Серпуховско-Тимирязевская линия")
    let line9Station7 = StationNode(name: "Дмитровская", line: "Серпуховско-Тимирязевская линия")
    let line9Station8 = StationNode(name: "Савёловская", line: "Серпуховско-Тимирязевская линия")
    let line9Station9 = StationNode(name: "Менделеевская", line: "Серпуховско-Тимирязевская линия")
    let line9Station10 = StationNode(name: "Цветной бульвар", line: "Серпуховско-Тимирязевская линия")
    let line9Station11 = StationNode(name: "Чеховская", line: "Серпуховско-Тимирязевская линия")
    let line9Station12 = StationNode(name: "Боровицкая", line: "Серпуховско-Тимирязевская линия")
    let line9Station13 = StationNode(name: "Полянка", line: "Серпуховско-Тимирязевская линия")
    let line9Station14 = StationNode(name: "Серпуховская", line: "Серпуховско-Тимирязевская линия")
    let line9Station15 = StationNode(name: "Тульская", line: "Серпуховско-Тимирязевская линия")
    let line9Station16 = StationNode(name: "Нагатинская", line: "Серпуховско-Тимирязевская линия")
    let line9Station17 = StationNode(name: "Нагорная", line: "Серпуховско-Тимирязевская линия")
    let line9Station18 = StationNode(name: "Нахимовский проспект", line: "Серпуховско-Тимирязевская линия")
    let line9Station19 = StationNode(name: "Севастопольская", line: "Серпуховско-Тимирязевская линия")
    let line9Station20 = StationNode(name: "Чертановская", line: "Серпуховско-Тимирязевская линия")
    let line9Station21 = StationNode(name: "Южная", line: "Серпуховско-Тимирязевская линия")
    let line9Station22 = StationNode(name: "Пражская", line: "Серпуховско-Тимирязевская линия")
    let line9Station23 = StationNode(name: "Улица Академика Янгеля", line: "Серпуховско-Тимирязевская линия")
    let line9Station24 = StationNode(name: "Аннино", line: "Серпуховско-Тимирязевская линия")
    let line9Station25 = StationNode(name: "Бульвар Дмитрия Донского", line: "Серпуховско-Тимирязевская линия")
    
    
    //Line 10 - Люблинско-Дмитровская линия
    let line10Station1 = StationNode(name: "Селигерская", line: "Люблинско-Дмитровская линия")
    let line10Station2 = StationNode(name: "Верхние Лихоборы", line: "Люблинско-Дмитровская линия")
    let line10Station3 = StationNode(name: "Окружная", line: "Люблинско-Дмитровская линия")
    let line10Station4 = StationNode(name: "Петровско-Разумовская", line: "Люблинско-Дмитровская линия")
    let line10Station5 = StationNode(name: "Фонвизинская", line: "Люблинско-Дмитровская линия")
    let line10Station6 = StationNode(name: "Бутырская", line: "Люблинско-Дмитровская линия")
    let line10Station7 = StationNode(name: "Марьина Роща", line: "Люблинско-Дмитровская линия")
    let line10Station8 = StationNode(name: "Достоевская", line: "Люблинско-Дмитровская линия")
    let line10Station9 = StationNode(name: "Трубная", line: "Люблинско-Дмитровская линия")
    let line10Station10 = StationNode(name: "Сретенский бульвар", line: "Люблинско-Дмитровская линия")
    let line10Station11 = StationNode(name: "Чкаловская", line: "Люблинско-Дмитровская линия")
    let line10Station12 = StationNode(name: "Римская", line: "Люблинско-Дмитровская линия")
    let line10Station13 = StationNode(name: "Крестьянская застава", line: "Люблинско-Дмитровская линия")
    let line10Station14 = StationNode(name: "Дубровка", line: "Люблинско-Дмитровская линия")
    let line10Station15 = StationNode(name: "Кожуховская", line: "Люблинско-Дмитровская линия")
    let line10Station16 = StationNode(name: "Печатники", line: "Люблинско-Дмитровская линия")
    let line10Station17 = StationNode(name: "Волжская", line: "Люблинско-Дмитровская линия")
    let line10Station18 = StationNode(name: "Люблино", line: "Люблинско-Дмитровская линия")
    let line10Station19 = StationNode(name: "Братиславская", line: "Люблинско-Дмитровская линия")
    let line10Station20 = StationNode(name: "Марьино", line: "Люблинско-Дмитровская линия")
    let line10Station21 = StationNode(name: "Борисово", line: "Люблинско-Дмитровская линия")
    let line10Station22 = StationNode(name: "Шипиловская", line: "Люблинско-Дмитровская линия")
    let line10Station23 = StationNode(name: "Зябликово", line: "Люблинско-Дмитровская линия")
    
    
    //Line 11 - БКЛ
    let line11Station1 = StationNode(name: "Савёловская", line: "Большая кольцевая линия")
    let line11Station2 = StationNode(name: "Петровский парк", line: "Большая кольцевая линия")
    let line11Station3 = StationNode(name: "ЦСКА", line: "Большая кольцевая линия")
    let line11Station4 = StationNode(name: "Полежаевская", line: "Большая кольцевая линия")
    let line11Station5 = StationNode(name: "Шелепиха", line: "Большая кольцевая линия")
    let line11Station6 = StationNode(name: "Выставочная", line: "Большая кольцевая линия")
    
    
    //Line 12 - Бутовская
    let line12Station1 = StationNode(name: "Битцевский парк", line: "Бутовская линия")
    let line12Station2 = StationNode(name: "Лесопарковая", line: "Бутовская линия")
    let line12Station3 = StationNode(name: "Улица Старокачаловская", line: "Бутовская линия")
    let line12Station4 = StationNode(name: "Улица Скобелевская", line: "Бутовская линия")
    let line12Station5 = StationNode(name: "Бульвар Адмирала Ушакова", line: "Бутовская линия")
    let line12Station6 = StationNode(name: "Улица Горчакова", line: "Бутовская линия")
    let line12Station7 = StationNode(name: "Бунинская Аллея", line: "Бутовская линия")
    
    
    //Line 14 - МЦК
    let line14Station1 = StationNode(name: "Ботанический сад", line: "Московское центральное кольцо")
    let line14Station2 = StationNode(name: "Ростокино", line: "Московское центральное кольцо")
    let line14Station3 = StationNode(name: "Белокаменная", line: "Московское центральное кольцо")
    let line14Station4 = StationNode(name: "Бульвар Рокоссовского", line: "Московское центральное кольцо")
    let line14Station5 = StationNode(name: "Локомотив", line: "Московское центральное кольцо")
    let line14Station6 = StationNode(name: "Измайлово", line: "Московское центральное кольцо")
    let line14Station7 = StationNode(name: "Соколиная гора", line: "Московское центральное кольцо")
    let line14Station8 = StationNode(name: "Шоссе Энтузиастов", line: "Московское центральное кольцо")
    let line14Station9 = StationNode(name: "Андроновка", line: "Московское центральное кольцо")
    let line14Station10 = StationNode(name: "Нижегородская", line: "Московское центральное кольцо")
    let line14Station11 = StationNode(name: "Новохохловская", line: "Московское центральное кольцо")
    let line14Station12 = StationNode(name: "Угрешская", line: "Московское центральное кольцо")
    let line14Station13 = StationNode(name: "Дубровка", line: "Московское центральное кольцо")
    let line14Station14 = StationNode(name: "Автозаводская", line: "Московское центральное кольцо")
    let line14Station15 = StationNode(name: "ЗИЛ", line: "Московское центральное кольцо")
    let line14Station16 = StationNode(name: "Верхние Котлы", line: "Московское центральное кольцо")
    let line14Station17 = StationNode(name: "Крымская", line: "Московское центральное кольцо")
    let line14Station18 = StationNode(name: "Площадь Гагарина", line: "Московское центральное кольцо")
    let line14Station19 = StationNode(name: "Лужники", line: "Московское центральное кольцо")
    let line14Station20 = StationNode(name: "Кутузовская", line: "Московское центральное кольцо")
    let line14Station21 = StationNode(name: "Деловой центр", line: "Московское центральное кольцо")
    let line14Station22 = StationNode(name: "Шелепиха", line: "Московское центральное кольцо")
    let line14Station23 = StationNode(name: "Хорошёво", line: "Московское центральное кольцо")
    let line14Station24 = StationNode(name: "Зорге", line: "Московское центральное кольцо")
    let line14Station25 = StationNode(name: "Панфиловская", line: "Московское центральное кольцо")
    let line14Station26 = StationNode(name: "Стрешнево", line: "Московское центральное кольцо")
    let line14Station27 = StationNode(name: "Балтийская", line: "Московское центральное кольцо")
    let line14Station28 = StationNode(name: "Коптево", line: "Московское центральное кольцо")
    let line14Station29 = StationNode(name: "Лихоборы", line: "Московское центральное кольцо")
    let line14Station30 = StationNode(name: "Окружная", line: "Московское центральное кольцо")
    let line14Station31 = StationNode(name: "Владыкино", line: "Московское центральное кольцо")
    
    
    //Line 15 - Некрасовская
    let line15Station1 = StationNode(name: "Электрозаводская", line: "Некрасовская линия")
    let line15Station2 = StationNode(name: "Лефортово", line: "Некрасовская линия")
    let line15Station3 = StationNode(name: "Авиамоторная", line: "Некрасовская линия")
    let line15Station4 = StationNode(name: "Нижегородская", line: "Некрасовская линия")
    let line15Station5 = StationNode(name: "Стахановская", line: "Некрасовская линия")
    let line15Station6 = StationNode(name: "Окская", line: "Некрасовская линия")
    let line15Station7 = StationNode(name: "Юго-Восточная", line: "Некрасовская линия")
    let line15Station8 = StationNode(name: "Косино", line: "Некрасовская линия")
    let line15Station9 = StationNode(name: "Улица Дмитриевского", line: "Некрасовская линия")
    let line15Station10 = StationNode(name: "Лухмановская", line: "Некрасовская линия")
    let line15Station11 = StationNode(name: "Некрасовка", line: "Некрасовская линия")
    
    
    //Line D1 - МЦД 1
    let lineD1Station1 = StationNode(name: "Лобня", line: "МЦД-1")
    let lineD1Station2 = StationNode(name: "Шереметьевская", line: "МЦД-1")
    let lineD1Station3 = StationNode(name: "Хлебниково", line: "МЦД-1")
    let lineD1Station4 = StationNode(name: "Водники", line: "МЦД-1")
    let lineD1Station5 = StationNode(name: "Долгопрудная", line: "МЦД-1")
    let lineD1Station6 = StationNode(name: "Новодачная", line: "МЦД-1")
    let lineD1Station7 = StationNode(name: "Марк", line: "МЦД-1")
    let lineD1Station8 = StationNode(name: "Лианозово", line: "МЦД-1")
    let lineD1Station9 = StationNode(name: "Бескудниково", line: "МЦД-1")
    let lineD1Station10 = StationNode(name: "Дегунино", line: "МЦД-1")
    let lineD1Station11 = StationNode(name: "Окружная", line: "МЦД-1")
    let lineD1Station12 = StationNode(name: "Тимирязевская", line: "МЦД-1")
    let lineD1Station13 = StationNode(name: "Савёловская", line: "МЦД-1")
    let lineD1Station14 = StationNode(name: "Белорусская", line: "МЦД-1")
    let lineD1Station15 = StationNode(name: "Беговая", line: "МЦД-1")
    let lineD1Station16 = StationNode(name: "Тестовская", line: "МЦД-1")
    let lineD1Station17 = StationNode(name: "Фили", line: "МЦД-1")
    let lineD1Station18 = StationNode(name: "Славянский бульвар", line: "МЦД-1")
    let lineD1Station19 = StationNode(name: "Кунцевская", line: "МЦД-1")
    let lineD1Station20 = StationNode(name: "Рабочий Посёлок", line: "МЦД-1")
    let lineD1Station21 = StationNode(name: "Сетунь", line: "МЦД-1")
    let lineD1Station22 = StationNode(name: "Немчиновка", line: "МЦД-1")
    let lineD1Station23 = StationNode(name: "Сколково", line: "МЦД-1")
    let lineD1Station24 = StationNode(name: "Баковка", line: "МЦД-1")
    let lineD1Station25 = StationNode(name: "Одинцово", line: "МЦД-1")
    
    
    //Line D2 - МЦД 2
    let lineD2Station1 = StationNode(name: "Нахабино", line: "МЦД-2")
    let lineD2Station2 = StationNode(name: "Аникеевка", line: "МЦД-2")
    let lineD2Station3 = StationNode(name: "Опалиха", line: "МЦД-2")
    let lineD2Station4 = StationNode(name: "Красногорская", line: "МЦД-2")
    let lineD2Station5 = StationNode(name: "Павшино", line: "МЦД-2")
    let lineD2Station6 = StationNode(name: "Пенягино", line: "МЦД-2")
    let lineD2Station7 = StationNode(name: "Волоколамская", line: "МЦД-2")
    let lineD2Station8 = StationNode(name: "Трикотажная", line: "МЦД-2")
    let lineD2Station9 = StationNode(name: "Тушинская", line: "МЦД-2")
    let lineD2Station10 = StationNode(name: "Покровское-Стрешнево", line: "МЦД-2")
    let lineD2Station11 = StationNode(name: "Стрешнево", line: "МЦД-2")
    let lineD2Station12 = StationNode(name: "Красный Балтиец", line: "МЦД-2")
    let lineD2Station13 = StationNode(name: "Гражданская", line: "МЦД-2")
    let lineD2Station14 = StationNode(name: "Дмитровская", line: "МЦД-2")
    let lineD2Station15 = StationNode(name: "Рижская", line: "МЦД-2")
    let lineD2Station16 = StationNode(name: "Каланчёвская", line: "МЦД-2")
    let lineD2Station17 = StationNode(name: "Курская", line: "МЦД-2")
    let lineD2Station18 = StationNode(name: "Москва-Товарная", line: "МЦД-2")
    let lineD2Station19 = StationNode(name: "Калитники", line: "МЦД-2")
    let lineD2Station20 = StationNode(name: "Новохохловская", line: "МЦД-2")
    let lineD2Station21 = StationNode(name: "Текстильщики", line: "МЦД-2")
    let lineD2Station22 = StationNode(name: "Кубанская", line: "МЦД-2")
    let lineD2Station23 = StationNode(name: "Депо", line: "МЦД-2")
    let lineD2Station24 = StationNode(name: "Перерва", line: "МЦД-2")
    let lineD2Station25 = StationNode(name: "Курьяново", line: "МЦД-2")
    let lineD2Station26 = StationNode(name: "Москворечье", line: "МЦД-2")
    let lineD2Station27 = StationNode(name: "Царицино", line: "МЦД-2")
    let lineD2Station28 = StationNode(name: "Покровское", line: "МЦД-2")
    let lineD2Station29 = StationNode(name: "Красный Строитель", line: "МЦД-2")
    let lineD2Station30 = StationNode(name: "Битца", line: "МЦД-2")
    let lineD2Station31 = StationNode(name: "Бутово", line: "МЦД-2")
    let lineD2Station32 = StationNode(name: "Щербинка", line: "МЦД-2")
    let lineD2Station33 = StationNode(name: "Остафьево", line: "МЦД-2")
    let lineD2Station34 = StationNode(name: "Силикатная", line: "МЦД-2")
    let lineD2Station35 = StationNode(name: "Подольск", line: "МЦД-2")
  
}


